In [1]:
%load_ext autoreload
%autoreload 2

In [6]:
import numpy as np

In [2]:
import sys
sys.path.append('../..')

In [96]:
from dstableFGM import dstableFGM, projectPSD, graddstableform, dstable_descent

In [111]:
A = np.random.normal(size=(50, 50), scale=2/np.sqrt(50))

In [112]:
np.linalg.eigvals(A)

array([-1.02412592+1.63174813j, -1.02412592-1.63174813j,
       -1.43143387+1.26082588j, -1.43143387-1.26082588j,
        1.90201869+0.52616136j,  1.90201869-0.52616136j,
        1.73153396+0.81296662j,  1.73153396-0.81296662j,
       -1.73899601+0.20112592j, -1.73899601-0.20112592j,
       -0.73521143+1.52545565j, -0.73521143-1.52545565j,
       -1.35396841+0.86567622j, -1.35396841-0.86567622j,
       -0.11711755+1.62622426j, -0.11711755-1.62622426j,
        0.15537611+1.63580787j,  0.15537611-1.63580787j,
        0.6531627 +1.47204138j,  0.6531627 -1.47204138j,
        0.78210331+1.33592841j,  0.78210331-1.33592841j,
        1.40326782+0.69556056j,  1.40326782-0.69556056j,
        1.51542783+0.08556979j,  1.51542783-0.08556979j,
        1.14463534+0.87648443j,  1.14463534-0.87648443j,
       -1.43636191+0.j        , -0.88623814+0.86902032j,
       -0.88623814-0.86902032j, -1.17823012+0.j        ,
        1.16076798+0.27477401j,  1.16076798-0.27477401j,
       -0.90027983+0.48682624j,

In [115]:
np.abs(np.linalg.eigvals(A))

array([9.68793551e-01, 8.60206240e-01, 8.60206240e-01, 7.89895823e-01,
       7.89895823e-01, 8.77206180e-01, 8.77206180e-01, 8.95120717e-01,
       8.95120717e-01, 8.69371334e-01, 8.69371334e-01, 8.58927635e-01,
       8.58927635e-01, 8.77758634e-01, 8.77758634e-01, 8.45738603e-01,
       8.45738603e-01, 6.79354109e-01, 6.79354109e-01, 8.87781603e-01,
       8.87781603e-01, 9.08744620e-01, 9.08744620e-01, 8.37882089e-01,
       8.37882089e-01, 8.45661524e-01, 8.45661524e-01, 8.42784869e-01,
       8.42784869e-01, 8.85511959e-01, 8.85511959e-01, 8.83359453e-01,
       8.83359453e-01, 8.85167544e-01, 8.85167544e-01, 9.08758441e-01,
       9.08758441e-01, 8.71693106e-01, 7.13430824e-01, 7.13430824e-01,
       6.31947060e-01, 6.31947060e-01, 4.44751816e-01, 5.25029900e-01,
       5.25029900e-01, 4.23060059e-01, 4.23060059e-01, 2.56527203e-01,
       2.56527203e-01, 1.03776099e-15])

In [113]:
A = dstable_descent(A, maxiter=200, tol=1e-3, init='default')

74.17274829659894
30.497482794185974
29.397279784490994
28.228762294739667
24.38429062910522
23.988090976407708
23.90082562039503
21.983904287738863
19.908228043995134
19.622071958517612
19.25809685662921
18.67627356548668
18.351923722654693
18.15463962814252
17.748049682768304
17.73990540389607
17.26647861624046
17.078278669088
16.979089194316604
16.822945375780026
16.6292115348484
16.594889900479227
16.321768981220966
16.295117802587377
16.26003464027483
16.000515724601556
15.99953554729062
15.99612899745185
15.79691604366839
15.60470457253746
15.46325338810223
15.443256171125903
15.392736158812816
15.245828510024861
15.1367348339071
15.134708316762035
15.097579755181728
14.95872658418211
14.856170303787398
14.793747486789764
14.740855199795107
14.72172922272734
14.620552714582342
14.56171583370149
14.517783403470553
14.50779021813237
14.404073497833453
14.34799518630886
14.3066010466975
14.291416419203998
14.200253053828973
14.148523074955598
14.107207625748257
14.081485040130808
14

In [94]:
A = dstableFGM(A)

74.30695086203905
Display of iteration number and error:
> /home/akumar/nse/neural_control/dstableFGM.py(171)dstableFGM()
    169         pdb.set_trace()
    170         # Display
--> 171         if display:
    172             if i % ndisplay == 0:
    173                 print('%2.0f:%2.3f - ',i ,e[i + 1])

9.327820096769747
[array(2.10078916e+14), array(1.09468501e+14), array(5.48950304e+13), array(1.9309674e+13), array(223.25758967), array(30.3139607)]


BdbQuit: 

(array([[ 0.9516448 -3.82132227e-205j, -0.0074041 -1.19203027e-205j,
          0.02645596+3.24155923e-205j, ...,  0.05701331+4.89295050e-205j,
         -0.09166026+4.44431050e-205j,  0.07481819+3.60646099e-205j],
        [-0.0074041 -1.19203027e-205j,  1.03521214-8.76353826e-205j,
         -0.06131114-1.66066035e-204j, ..., -0.06267445-1.06455763e-204j,
         -0.02376924+1.74438901e-205j,  0.05510339-2.29758374e-205j],
        [ 0.02645596+3.24155923e-205j, -0.06131114-1.66066035e-204j,
          1.04492004+3.42629166e-206j, ..., -0.03292833-5.98794572e-205j,
          0.06278156+1.35216262e-204j, -0.03512779-5.18630483e-205j],
        ...,
        [ 0.05701331+4.89295050e-205j, -0.06267445-1.06455763e-204j,
         -0.03292833-5.98794572e-205j, ...,  1.05577842-4.11563271e-206j,
          0.01141149+5.72136725e-205j,  0.03007406-3.36837073e-205j],
        [-0.09166026+4.44431050e-205j, -0.02376924+1.74438901e-205j,
          0.06278156+1.35216262e-204j, ...,  0.01141149+5.72136725

In [44]:
import torch
import scipy

In [43]:
# Step (1): Explicitly check the gradients
# Step (2): Check against the examples provided in the paper
# Step (3): Start many random initilizations

In [81]:
A = np.random.normal(size=(50, 50), scale=2/np.sqrt(50))
U, H = scipy.linalg.polar(A)
B = projectPSD(H, 1e-6, 1 - 1e-6)
At = torch.tensor(A, requires_grad=True)
S = np.diag(np.random.uniform(0.1, 0.9, size=(50,)))
St = torch.tensor(S, requires_grad=True)
Ut = torch.tensor(U, requires_grad=True)
Bt = torch.tensor(B, requires_grad=True)

In [82]:
loss = torch.pow(torch.norm(At - torch.chain_matmul(torch.inverse(St), Ut, Bt, St)), 2)

In [83]:
loss.backward()

In [85]:
St.grad

tensor([[ 3.0890e+00,  1.1302e+00, -5.1995e+00,  ..., -4.1789e-01,
         -4.1198e-01,  2.5708e+00],
        [-1.8304e+00,  1.2016e+01,  2.5484e-01,  ...,  6.0706e-03,
          2.5344e+00,  2.2524e+00],
        [-5.3120e+00, -2.4581e+00, -3.8214e+01,  ..., -9.8562e-01,
          2.8818e+00,  3.7360e+00],
        ...,
        [ 1.2736e+00,  1.7175e+00,  1.5691e+00,  ...,  2.9873e+00,
          4.6111e-01,  6.2369e-01],
        [-1.7762e+00,  4.5122e+00, -5.5682e-01,  ...,  1.4198e-01,
          6.7325e-01, -1.4837e-01],
        [ 8.6948e-01,  4.3131e+00,  9.8137e-01,  ...,  2.5350e+00,
          1.4256e+00, -4.7278e+00]], dtype=torch.float64)

In [86]:
e, gS, gU, gB = graddstableform(A, np.eye(50), U, B, return_grad=True)

In [88]:
np.linalg.norm(gS - St.grad.detach().numpy())

524.993263304741

In [80]:
np.linalg.norm(gU - Ut.grad.detach().numpy())

34.09716910329542